export const homeObjectOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "info.objectOne.topLine",
  headline: "info.objectOne.healine",
  description: "info.objectOne.description",
  buttonLabel: "info.objectOne.buttonLabel",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjectTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "info.objectTwo.topLine",
  headline: "info.objectTwo.healine",
  description: "info.objectTwo.description",
  buttonLabel: "info.objectTwo.buttonLabel",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
};
